
import { Order, DailySummary } from '@/types';
import jsPDF from 'jspdf';

// Map rider numbers to names
const getRiderName = (riderNumber?: string): string => {
  // Rider names are already in the correct format
  return riderNumber || '';
};

export const generateDailyReport = (summary: DailySummary, orders: Order[], adminUsername?: string): string => {
  const today = new Date().toLocaleDateString();
  const todaysOrders = orders.filter(order => {
    const orderDate = new Date(order.timestamp);
    const todayDate = new Date();
    return orderDate.toDateString() === todayDate.toDateString();
  });

  let report = `TIMELEXX INN - DAILY SALES REPORT\n`;
  report += `Date: ${today}\n`;
  if (adminUsername) {
    report += `Report generated by: ${adminUsername}\n`;
  }
  report += `${'='.repeat(50)}\n\n`;

  // Summary Section
  report += `DAILY SUMMARY\n`;
  report += `${'-'.repeat(20)}\n`;
  report += `Total Orders: ${summary.totalOrders}\n`;
  report += `Total Revenue: ₵${summary.totalRevenue}\n`;
  report += `Average Order Value: ₵${summary.totalOrders > 0 ? Math.round(summary.totalRevenue / summary.totalOrders) : 0}\n\n`;

  // Payment Method Summary
  const deliveredOrders = todaysOrders.filter(order => order.status === 'delivered');
  const cashOrders = deliveredOrders.filter(order => order.paymentMethod === 'Cash');
  const momoOrders = deliveredOrders.filter(order => order.paymentMethod === 'MoMo');
  const cashRevenue = cashOrders.reduce((sum, order) => sum + order.total, 0);
  const momoRevenue = momoOrders.reduce((sum, order) => sum + order.total, 0);

  report += `PAYMENT METHOD BREAKDOWN\n`;
  report += `${'-'.repeat(30)}\n`;
  report += `Cash Payments: ${cashOrders.length} orders - ₵${cashRevenue}\n`;
  report += `MoMo Payments: ${momoOrders.length} orders - ₵${momoRevenue}\n\n`;

  // Best and Worst Performing Items
  report += `PERFORMANCE ANALYSIS\n`;
  report += `${'-'.repeat(30)}\n`;
  if (summary.bestSelling) {
    report += `Best Selling Item: ${summary.bestSelling.name}\n`;
    report += `  - Orders: ${summary.ordersByMeal[summary.bestSelling.name]}\n`;
    report += `  - Revenue: ₵${summary.revenueByMeal[summary.bestSelling.name]}\n\n`;
  }
  
  if (summary.worstSelling) {
    report += `Least Selling Item: ${summary.worstSelling.name}\n`;
    report += `  - Orders: ${summary.ordersByMeal[summary.worstSelling.name]}\n`;
    report += `  - Revenue: ₵${summary.revenueByMeal[summary.worstSelling.name]}\n\n`;
  }

  // Detailed Sales by Item
  report += `SALES BY MENU ITEM\n`;
  report += `${'-'.repeat(25)}\n`;
  Object.entries(summary.ordersByMeal).forEach(([meal, count]) => {
    const revenue = summary.revenueByMeal[meal] || 0;
    report += `${meal}:\n`;
    report += `  - Quantity Sold: ${count}\n`;
    report += `  - Revenue: ₵${revenue}\n\n`;
  });

  // Order Details
  report += `ORDER DETAILS\n`;
  report += `${'-'.repeat(20)}\n`;
  const cancelledOrders = todaysOrders.filter(order => order.status === 'cancelled');
  const pendingOrders = todaysOrders.filter(order => order.status === 'pending');

  report += `Delivered Orders: ${deliveredOrders.length}\n`;
  report += `Cancelled Orders: ${cancelledOrders.length}\n`;
  report += `Pending Orders: ${pendingOrders.length}\n\n`;

  // Individual Orders
  if (deliveredOrders.length > 0) {
    report += `DELIVERED ORDERS LIST\n`;
    report += `${'-'.repeat(30)}\n`;
    deliveredOrders.forEach(order => {
      report += `Order #${order.id.slice(-6)} - ${order.timestamp.toLocaleDateString()} at ${order.timestamp.toLocaleTimeString()}\n`;
      if (order.customerName) {
        report += `  Customer: ${order.customerName}\n`;
      }
      if (order.customerNumber) {
        report += `  Phone: ${order.customerNumber}\n`;
      }
      if (order.customerLocation) {
        report += `  Location: ${order.customerLocation.address}\n`;
        report += `  Coordinates: ${order.customerLocation.coordinates[0]}, ${order.customerLocation.coordinates[1]}\n`;
      }
      report += `  Type: ${order.orderType.toUpperCase()}`;
      if (order.riderNumber) {
        report += ` (${getRiderName(order.riderNumber)})`;
      }
      report += `\n`;
      if (order.paymentMethod) {
        report += `  Payment Method: ${order.paymentMethod}\n`;
      }
      order.items.forEach(item => {
        report += `  - ${item.menuItem.name} x${item.quantity} = ₵${item.menuItem.price * item.quantity}\n`;
      });
      report += `  Total: ₵${order.total}\n\n`;
    });
  }

  if (cancelledOrders.length > 0) {
    report += `CANCELLED ORDERS LIST\n`;
    report += `${'-'.repeat(30)}\n`;
    cancelledOrders.forEach(order => {
      report += `Order #${order.id.slice(-6)} - ${order.timestamp.toLocaleDateString()} at ${order.timestamp.toLocaleTimeString()}\n`;
      if (order.customerName) {
        report += `  Customer: ${order.customerName}\n`;
      }
      if (order.customerNumber) {
        report += `  Phone: ${order.customerNumber}\n`;
      }
      if (order.customerLocation) {
        report += `  Location: ${order.customerLocation.address}\n`;
        report += `  Coordinates: ${order.customerLocation.coordinates[0]}, ${order.customerLocation.coordinates[1]}\n`;
      }
      report += `  Type: ${order.orderType.toUpperCase()}`;
      if (order.riderNumber) {
        report += ` (${getRiderName(order.riderNumber)})`;
      }
      report += `\n`;
      if (order.paymentMethod) {
        report += `  Payment Method: ${order.paymentMethod}\n`;
      }
      order.items.forEach(item => {
        report += `  - ${item.menuItem.name} x${item.quantity} = ₵${item.menuItem.price * item.quantity}\n`;
      });
      report += `  Total: ₵${order.total}\n\n`;
    });
  }

  report += `${'='.repeat(50)}\n`;
  report += `Report Generated: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}\n`;
  if (adminUsername) {
    report += `Report generated by: ${adminUsername}\n`;
  }
  report += `Timelexx Inn Order Management System\n`;

  return report;
};

export const downloadReportAsPDF = (summary: DailySummary, orders: Order[], adminUsername?: string): void => {
  console.log('Generating PDF report...');
  
  const reportContent = generateDailyReport(summary, orders, adminUsername);
  const doc = new jsPDF();
  
  // Set font to courier for better character support and monospacing
  doc.setFont('courier');
  doc.setFontSize(9);
  
  // Split content into lines and add to PDF
  const lines = reportContent.split('\n');
  let yPosition = 15;
  const lineHeight = 4;
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 10;
  const maxWidth = pageWidth - (margin * 2);
  
  lines.forEach((line) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 15) {
      doc.addPage();
      yPosition = 15;
    }
    
    // Split long lines to fit page width
    const splitLines = doc.splitTextToSize(line, maxWidth);
    splitLines.forEach((splitLine: string) => {
      if (yPosition > pageHeight - 15) {
        doc.addPage();
        yPosition = 15;
      }
      doc.text(splitLine, margin, yPosition);
      yPosition += lineHeight;
    });
  });
  
  // Generate filename with current date and admin username
  const today = new Date();
  const dateString = today.toISOString().split('T')[0];
  const timeString = today.toTimeString().split(' ')[0].replace(/:/g, '-');
  const adminSuffix = adminUsername ? `_by_${adminUsername}` : '';
  const filename = `Timelexx_Inn_Report_${dateString}_${timeString}${adminSuffix}.pdf`;
  
  // Download the PDF
  doc.save(filename);
  console.log(`Report downloaded as ${filename}`);
};
