// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seznzhtgkjzvfrznpljt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlem56aHRna2p6dmZyem5wbGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDg1NzIsImV4cCI6MjA2NTMyNDU3Mn0.I9wPBrVi5BG3hUBqlCsoXsxQ_gk6sgaDlWpBLQWIf8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});